swagger: "2.0"
info:
  title: Fastify API
  description: API description in Markdown.
  version: 1.0.0
host: localhost:9000
basePath: /
schemes:
  - http
paths:
  /users/user:
    post:
      summary: Add or update a user.
      parameters:
        - in: body
          required: true
          name: user
          schema:
            $ref: '#/definitions/User'

      responses:
        201:
          description: User Added
        400:
          description: Bad request

  /users:
    get:
      summary: Get the list of users
      responses:
        200:
          description: Successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
        400:
          description: Bad request


definitions:
  User:
    properties:
      id:
        type: number
      name:
        type: string
      gender:
        type: string
      address:
        type: string
    required:
      - id
      - name
      - gender